### ISSUE TITLE
Order regions intuitively in theme info.yml

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/cwd_project#17]
Something I've seen @sbbutkcin do on his projects -- makes total sense -- put the regions in the same order as they're rendered on pages/in the DOM.
https://github.com/CU-CommunityApps/cwd_project/blob/master/cwd_project.info.yml

Only downside I can think of is maybe it's handy to have the "content" region at the top.......? But idk, I think it's handy and less confusing to make the order what the order "really is."

_(REMINDER: The order the regions are listed in the theme `.info.yml` file is how the regions are listed in the Drupal Block layout admin UI.)_

**Comment by alisonjo315** [comment]
"Assignment" -- I could do it, but it would probably be easier for a designer to do it, they'd probably "just know" the order off the top of their head...?

**Comment by alisonjo315** [comment]
@ama39 Could you please look at this region order, and tell me if it correctly reflects the order we render block regions (by default / on CD Demo)? -- [here's the updated version of cwd_project.info.yml](https://github.com/CU-CommunityApps/cwd_project/blob/eb7b2fc3a603021d4f79a5d0f838296761d26269/cwd_project.info.yml), or, I've pasted the `regions:` section here in this comment:

```

# These regions match the base theme, but will fully override the base theme's definitions. As such, you can add or remove regions as needed.
regions:
  nav_main: 'Main Navigation'
  nav_utility: 'Utility Navigation'
  nav_breadcrumb: 'Breadcrumb navigation'
  content_header: 'Content Header'
  content: 'Content'
  content_footer: 'Content Footer'
  sidebar_primary: 'Primary Sidebar (Top)'
  sidebar_secondary: 'Secondary Sidebar (Bottom)'
  supplementary: 'Supplementary Region 1'
  supplementary2: 'Supplementary Region 2'
  footer_primary: 'Primary Footer Region'
  footer_secondary: 'Secondary Footer Region'
  subfooter: 'Subfooter'
```
